name: Ruby

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      uses: ./.github/actions/setup

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ./coverage/lcov/code_coverage_test.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
